In [1]:
import pandas as pd

In [5]:
url = ('https://github.com/jovianosilveira/materiais_apoio_cursos/blob/main/Palestras/202104%20-%20Guia%20Essencial%20Python/dados/dia01.xlsx?raw=true')

In [7]:
dia1 = pd.read_excel(url)

In [8]:
dia1

         DATA  HORA  GASOLINA  ALCOOL  DIESEL
0  2000-01-01     0       515     170     144
1  2000-01-01     1       686     329     274
2  2000-01-01     2       686     302     130
3  2000-01-01     3       480     187     182
4  2000-01-01     4       789     363     237
5  2000-01-01     5       755     302     279
6  2000-01-01     6      1030     443     185
7  2000-01-01     7      1030     474     237
8  2000-01-01     8      1064     447     192
9  2000-01-01     9       755     347     128
10 2000-01-01    10       789     395     229
11 2000-01-01    11      1270     495     419
12 2000-01-01    12      1098     351     198
13 2000-01-01    13      1270     584     368
14 2000-01-01    14       961     288     144
15 2000-01-01    15      1030     453     330
16 2000-01-01    16      1030     319     402
17 2000-01-01    17      1338     468     254
18 2000-01-01    18      1304     482     261
19 2000-01-01    19      1373     563     412
20 2000-01-01    20       961     384     279
21 2000-01-01    21      1030     505     391
22 2000-01-01    22       480     230      77
23 2000-01-01    23       446     161      98

In [10]:
url_dia01 = ('https://github.com/jovianosilveira/materiais_apoio_cursos/blob/main/Palestras/202104%20-%20Guia%20Essencial%20Python/dados/dia01.xlsx?raw=true')
url_dia02 = ('https://github.com/jovianosilveira/materiais_apoio_cursos/blob/main/Palestras/202104%20-%20Guia%20Essencial%20Python/dados/dia02.xlsx?raw=true')
url_dia03 = ('https://github.com/jovianosilveira/materiais_apoio_cursos/blob/main/Palestras/202104%20-%20Guia%20Essencial%20Python/dados/dia03.xlsx?raw=true')

In [18]:
dia01 = pd.read_excel(url_dia01)
dia02 = pd.read_excel(url_dia02)
dia03 = pd.read_excel(url_dia03)

In [34]:
dias = pd.concat([dia02, dia03])
dias

         DATA  HORA  GASOLINA  ALCOOL  DIESEL
0  2000-01-02     0       329     141      72
1  2000-01-02     1       625     294     125
2  2000-01-02     2       362     123      65
3  2000-01-02     3       362     181      83
4  2000-01-02     4       822     279     304
5  2000-01-02     5       724     297     217
6  2000-01-02     6      1283     552     269
7  2000-01-02     7      1086     424     228
8  2000-01-02     8      1053     474     390
9  2000-01-02     9       724     282     203
10 2000-01-02    10       757     333     167
11 2000-01-02    11      1151     437     380
12 2000-01-02    12      1283     616     359
13 2000-01-02    13      1086     326     174
14 2000-01-02    14       658     309     230
15 2000-01-02    15       822     279     329
16 2000-01-02    16      1250     538     288
17 2000-01-02    17      1184     497     296
18 2000-01-02    18       987     424     395
19 2000-01-02    19      1053     390     390
20 2000-01-02    20       987     316     227
21 2000-01-02    21       691     235     104
22 2000-01-02    22       395     154      59
23 2000-01-02    23       329     161     122
0  2000-01-03     0       562     236     124
1  2000-01-03     1       562     236     214
2  2000-01-03     2       533     187     165
3  2000-01-03     3       505     177      76
4  2000-01-03     4       786     322     275
5  2000-01-03     5       758     326     303
6  2000-01-03     6      1067     405     363
7  2000-01-03     7       955     392     306
8  2000-01-03     8       955     372     382
9  2000-01-03     9       590     177     212
10 2000-01-03    10       758     364     197
11 2000-01-03    11       842     404     177
12 2000-01-03    12      1067     352     384
13 2000-01-03    13      1039     499     395
14 2000-01-03    14       758     235     296
15 2000-01-03    15       758     334     197
16 2000-01-03    16      1095     427     263
17 2000-01-03    17       955     382     334
18 2000-01-03    18      1123     472     326
19 2000-01-03    19       955     296     181
20 2000-01-03    20       646     245     258
21 2000-01-03    21       590     218     189
22 2000-01-03    22       449     198     130
23 2000-01-03    23       393     122     126

In [33]:
print(dias)

         DATA  HORA  GASOLINA  ALCOOL  DIESEL
0  2000-01-02     0       329     141      72
1  2000-01-02     1       625     294     125
2  2000-01-02     2       362     123      65
3  2000-01-02     3       362     181      83
4  2000-01-02     4       822     279     304
5  2000-01-02     5       724     297     217
6  2000-01-02     6      1283     552     269
7  2000-01-02     7      1086     424     228
8  2000-01-02     8      1053     474     390
9  2000-01-02     9       724     282     203
10 2000-01-02    10       757     333     167
11 2000-01-02    11      1151     437     380
12 2000-01-02    12      1283     616     359
13 2000-01-02    13      1086     326     174
14 2000-01-02    14       658     309     230
15 2000-01-02    15       822     279     329
16 2000-01-02    16      1250     538     288
17 2000-01-02    17      1184     497     296
18 2000-01-02    18       987     424     395
19 2000-01-02    19      1053     390     390
20 2000-01-02    20       987     316     227
21 2000-01-02    21       691     235     104
22 2000-01-02    22       395     154      59
23 2000-01-02    23       329     161     122
0  2000-01-03     0       562     236     124
1  2000-01-03     1       562     236     214
2  2000-01-03     2       533     187     165
3  2000-01-03     3       505     177      76
4  2000-01-03     4       786     322     275
5  2000-01-03     5       758     326     303
6  2000-01-03     6      1067     405     363
7  2000-01-03     7       955     392     306
8  2000-01-03     8       955     372     382
9  2000-01-03     9       590     177     212
10 2000-01-03    10       758     364     197
11 2000-01-03    11       842     404     177
12 2000-01-03    12      1067     352     384
13 2000-01-03    13      1039     499     395
14 2000-01-03    14       758     235     296
15 2000-01-03    15       758     334     197
16 2000-01-03    16      1095     427     263
17 2000-01-03    17       955     382     334
18 2000-01-03    18      1123     472     326
19 2000-01-03    19       955     296     181
20 2000-01-03    20       646     245     258
21 2000-01-03    21       590     218     189
22 2000-01-03    22       449     198     130
23 2000-01-03    23       393     122     126

In [37]:
dias.head()

        DATA  HORA  GASOLINA  ALCOOL  DIESEL
0 2000-01-02     0       329     141      72
1 2000-01-02     1       625     294     125
2 2000-01-02     2       362     123      65
3 2000-01-02     3       362     181      83
4 2000-01-02     4       822     279     304

In [38]:
dias.tail()

         DATA  HORA  GASOLINA  ALCOOL  DIESEL
19 2000-01-03    19       955     296     181
20 2000-01-03    20       646     245     258
21 2000-01-03    21       590     218     189
22 2000-01-03    22       449     198     130
23 2000-01-03    23       393     122     126

In [41]:
pd.options.display.max_rows = 100

In [43]:
dias.reset_index(drop=True)

         DATA  HORA  GASOLINA  ALCOOL  DIESEL
0  2000-01-02     0       329     141      72
1  2000-01-02     1       625     294     125
2  2000-01-02     2       362     123      65
3  2000-01-02     3       362     181      83
4  2000-01-02     4       822     279     304
5  2000-01-02     5       724     297     217
6  2000-01-02     6      1283     552     269
7  2000-01-02     7      1086     424     228
8  2000-01-02     8      1053     474     390
9  2000-01-02     9       724     282     203
10 2000-01-02    10       757     333     167
11 2000-01-02    11      1151     437     380
12 2000-01-02    12      1283     616     359
13 2000-01-02    13      1086     326     174
14 2000-01-02    14       658     309     230
15 2000-01-02    15       822     279     329
16 2000-01-02    16      1250     538     288
17 2000-01-02    17      1184     497     296
18 2000-01-02    18       987     424     395
19 2000-01-02    19      1053     390     390
20 2000-01-02    20       987     316     227
21 2000-01-02    21       691     235     104
22 2000-01-02    22       395     154      59
23 2000-01-02    23       329     161     122
24 2000-01-03     0       562     236     124
25 2000-01-03     1       562     236     214
26 2000-01-03     2       533     187     165
27 2000-01-03     3       505     177      76
28 2000-01-03     4       786     322     275
29 2000-01-03     5       758     326     303
30 2000-01-03     6      1067     405     363
31 2000-01-03     7       955     392     306
32 2000-01-03     8       955     372     382
33 2000-01-03     9       590     177     212
34 2000-01-03    10       758     364     197
35 2000-01-03    11       842     404     177
36 2000-01-03    12      1067     352     384
37 2000-01-03    13      1039     499     395
38 2000-01-03    14       758     235     296
39 2000-01-03    15       758     334     197
40 2000-01-03    16      1095     427     263
41 2000-01-03    17       955     382     334
42 2000-01-03    18      1123     472     326
43 2000-01-03    19       955     296     181
44 2000-01-03    20       646     245     258
45 2000-01-03    21       590     218     189
46 2000-01-03    22       449     198     130
47 2000-01-03    23       393     122     126

In [49]:
dia01 = dia01.describe()
dia01

            HORA     GASOLINA      ALCOOL      DIESEL
count   8.000000     8.000000    8.000000    8.000000
mean    9.711830   435.926752  199.394463  130.715587
std     6.758664   410.173124  194.300047  123.230458
min     0.000000     8.000000    8.000000    8.000000
25%     7.427965   144.634052   63.348117   48.725724
50%     8.492196   451.487958  205.070783  131.378905
75%    10.705756   519.717883  225.921735  147.894883
max    24.000000  1283.000000  616.000000  395.000000

In [50]:
stats = dias.describe()
stats

                      DATA       HORA     GASOLINA      ALCOOL      DIESEL
count                   48  48.000000    48.000000   48.000000   48.000000
mean   2000-01-02 12:00:00  11.500000   806.333333  321.666667  236.437500
min    2000-01-02 00:00:00   0.000000   329.000000  122.000000   59.000000
25%    2000-01-02 00:00:00   5.750000   590.000000  235.000000  166.500000
50%    2000-01-02 12:00:00  11.500000   772.000000  319.000000  227.500000
75%    2000-01-03 00:00:00  17.250000  1053.000000  404.250000  311.000000
max    2000-01-03 00:00:00  23.000000  1283.000000  616.000000  395.000000
std                    NaN   6.995439   274.300994  120.909907  102.155681

In [52]:
target = stats['GASOLINA']['50%']
target

772.0

In [53]:
dias.query(' GASOLINA <= 772 ')

         DATA  HORA  GASOLINA  ALCOOL  DIESEL
0  2000-01-02     0       329     141      72
1  2000-01-02     1       625     294     125
2  2000-01-02     2       362     123      65
3  2000-01-02     3       362     181      83
5  2000-01-02     5       724     297     217
9  2000-01-02     9       724     282     203
10 2000-01-02    10       757     333     167
14 2000-01-02    14       658     309     230
21 2000-01-02    21       691     235     104
22 2000-01-02    22       395     154      59
23 2000-01-02    23       329     161     122
0  2000-01-03     0       562     236     124
1  2000-01-03     1       562     236     214
2  2000-01-03     2       533     187     165
3  2000-01-03     3       505     177      76
5  2000-01-03     5       758     326     303
9  2000-01-03     9       590     177     212
10 2000-01-03    10       758     364     197
14 2000-01-03    14       758     235     296
15 2000-01-03    15       758     334     197
20 2000-01-03    20       646     245     258
21 2000-01-03    21       590     218     189
22 2000-01-03    22       449     198     130
23 2000-01-03    23       393     122     126

In [54]:
dias.query(' GASOLINA <= @target ')

         DATA  HORA  GASOLINA  ALCOOL  DIESEL
0  2000-01-02     0       329     141      72
1  2000-01-02     1       625     294     125
2  2000-01-02     2       362     123      65
3  2000-01-02     3       362     181      83
5  2000-01-02     5       724     297     217
9  2000-01-02     9       724     282     203
10 2000-01-02    10       757     333     167
14 2000-01-02    14       658     309     230
21 2000-01-02    21       691     235     104
22 2000-01-02    22       395     154      59
23 2000-01-02    23       329     161     122
0  2000-01-03     0       562     236     124
1  2000-01-03     1       562     236     214
2  2000-01-03     2       533     187     165
3  2000-01-03     3       505     177      76
5  2000-01-03     5       758     326     303
9  2000-01-03     9       590     177     212
10 2000-01-03    10       758     364     197
14 2000-01-03    14       758     235     296
15 2000-01-03    15       758     334     197
20 2000-01-03    20       646     245     258
21 2000-01-03    21       590     218     189
22 2000-01-03    22       449     198     130
23 2000-01-03    23       393     122     126